package salvatoreassennato.gestionedispositiviaziendali.payloads_Utenti_Dispositivi;

import salvatoreassennato.gestionedispositiviaziendali.entities.Stato_Dispositivo;
import salvatoreassennato.gestionedispositiviaziendali.entities.Tipologia;
import salvatoreassennato.gestionedispositiviaziendali.entities.Utente;

public record NewDispositivoDTO(Utente utente, Tipologia tipologia, Stato_Dispositivo stato_dispositivo) {
}
